
import { config } from 'dotenv';
config();

import '@/ai/flows/generate-report-summary.ts';
import '@/ai/flows/generate-lesson-plan.ts';
import '@/ai/flows/mwalimu-ai-flow.ts';
import '@/ai/flows/mwalimu-ai-types.ts';
import '@/ai/flows/generate-scheme-of-work.ts';
import '@/ai/flows/generate-rubric.ts';
import '@/ai/flows/classroom-compass-flow.ts';
import '@/ai/flows/classroom-compass-types.ts';
import '@/ai/flows/generate-worksheet.ts';
import '@/ai/flows/differentiate-worksheet.ts';
import '@/ai/flows/improve-lesson-plan.ts';
import '@/ai/flows/improve-lesson-plan-types.ts';
import '@/ai/flows/generate-dashboard-summary.ts';
import '@/ai/flows/generate-dashboard-summary-types.ts';
import '@/ai/flows/school-head-consultant.ts';
import '@/ai/flows/school-head-consultant-types.ts';
import '@/ai/flows/generate-county-summary.ts';
import '@/ai/flows/generate-county-summary-types.ts';
import '@/ai/flows/ingest-curriculum.ts';
import '@/curriculum/pp1-mathematics-activities.ts';
import '@/curriculum/pp1-language-activities.ts';
import '@/curriculum/pp2-environmental-activities.ts';
import '@/curriculum/pp2-cre.ts';
import '@/curriculum/pp2-creative-arts.ts';
import '@/curriculum/grade6-social-studies.ts';
import '@/curriculum/pp2-language-activities.ts';
import '@/curriculum/pp2-mathematics-activities.ts';
import '@/curriculum/grade1-creative-activities.ts';
import '@/curriculum/grade1-english-language-activities.ts';
import '@/curriculum/grade1-indigenous-language.ts';
import '@/curriculum/grade1-kiswahili-language-activities.ts';
import '@/curriculum/grade1-mathematics-activities.ts';
